name: Build and Push Docker Image

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'liberica'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository_owner }}/performance-http-java:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/performance-http-java:${{ github.run_number }}

      - name: Image metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/performance-http-java
